'use strict';
const $=id=>document.getElementById(id);
const ids=['salary','extraFixed','extraVariable','housing','loans','domestic','fixedFees','otherCommitment','groceries','utilities','transport','health','education','dining','shopping','subscriptions','travelGifts','otherPersonal','saving','investment','emergencyMonths','emergencyCurrent','emergencyContribution','goalTarget','goalCurrent','goalMonths','goalUnit'];
let period='monthly', baseline=null, current={};
const n=id=>Number($(id)?.value||0);
const sum=a=>a.reduce((t,i)=>t+n(i),0);
const money=v=>new Intl.NumberFormat('ar-AE',{maximumFractionDigits:0}).format(Number(v)||0)+' د.إ';
const rawMoney=v=>new Intl.NumberFormat('ar-AE',{maximumFractionDigits:0}).format(Number(v)||0);
const multiplier=()=>period==='annual'?12:1;
const shown=v=>money(v*multiplier());
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2600)}
function safeSet(k,v){try{localStorage.setItem(k,v);return true}catch(e){return false}}
function safeGet(k,fallback=''){try{return localStorage.getItem(k)||fallback}catch(e){return fallback}}
function values(){const income=sum(['salary','extraFixed','extraVariable']),commit=sum(['housing','loans','domestic','fixedFees','otherCommitment']),essential=sum(['groceries','utilities','transport','health','education']),personal=sum(['dining','shopping','subscriptions','travelGifts','otherPersonal']),expenses=commit+essential+personal,saving=n('saving'),investment=n('investment'),after=income-expenses-saving-investment,target=(commit+essential)*(n('emergencyMonths')||6),emergency=n('emergencyCurrent'),emergencyContribution=n('emergencyContribution');return{income,commit,essential,personal,expenses,saving,investment,after,target,emergency,emergencyContribution}}
function setText(id,text){const el=$(id);if(el)el.textContent=text}
function setPeriod(p){period=p;$('monthlyBtn').classList.toggle('active',p==='monthly');$('annualBtn').classList.toggle('active',p==='annual');setText('periodLabel',p==='monthly'?'عرض شهري':'عرض سنوي');calc()}
function calc(){
  current=values(); const v=current;
  setText('totalIncome',shown(v.income)); setText('totalCommitments',shown(v.commit)); setText('totalExpenses',shown(v.expenses)); setText('plannedAllocations',shown(v.saving+v.investment)); setText('availableAfterPlan',shown(v.after));
  $('availableAfterPlan').parentElement.classList.toggle('bad',v.after<0);
  const ratio=v.income?v.expenses/v.income*100:0;
  let c='info',msg='أدخل بياناتك لرؤية قراءة إنتوى لوضعك المالي.';
  if(v.income){
    if(v.income-v.expenses<0){c='bad';msg='مصروفاتك أعلى من دخلك. الأولوية لإيقاف العجز قبل إضافة خطة استثمار.'}
    else if(v.after<0){c='warn';msg='خطة الادخار والاستثمار الحالية أعلى من الفائض المتاح.'}
    else if(v.target>v.emergency&&v.investment>0){c='warn';msg='لديك فائض، لكن صندوق الطوارئ لم يصل بعد إلى الهدف الذي اخترته.'}
    else{c='ok';msg='الخطة الحالية تترك فائضاً بعد المصروفات والادخار والاستثمار. راجعها دورياً عند تغير دخلك أو التزاماتك.'}
  }
  $('statusBox').className='status '+c; setText('statusBox',msg); updateDonut(v,ratio);
  setText('annualIncome',money(v.income*12)); setText('annualSpend',money(v.expenses*12)); setText('annualSave',money(v.saving*12)); setText('annualInvest',money(v.investment*12)); setText('annualAfter',money(v.after*12)); setText('annualAllocated',money((v.saving+v.investment)*12)); setText('emergencyTarget',money(v.target));
  const gap=Math.max(0,v.target-v.emergency),eta=gap===0?'مكتمل':v.emergencyContribution>0?Math.ceil(gap/v.emergencyContribution)+' شهر':'حدد مبلغاً شهرياً';
  setText('emergencyEta',eta); setText('emergencyHint',gap===0?'صندوق الطوارئ وصل إلى الهدف المختار.':'المتبقي لصندوق الطوارئ '+money(gap)+(v.emergencyContribution>0?' — تقريباً '+Math.ceil(gap/v.emergencyContribution)+' شهر للوصول للهدف.':' — أضف مبلغاً شهرياً لحساب المدة.'));
  drawAnnualChart(v); drawTimeline(v); updateSimulation(); updateComparison(); updateGoal(); persist();
}
function updateDonut(v,ratio){const total=Math.max(v.income,v.commit+v.essential+v.personal+v.saving+v.investment+Math.max(0,v.after),1),parts=[v.commit,v.essential,v.personal,v.saving+v.investment,Math.max(0,v.after)],colors=['#3b0d1d','#b9a28b','#7b8f86','#967128','#d9d3cd'];let acc=0,stops=[];parts.forEach((x,i)=>{let start=acc,end=acc+x/total*100;stops.push(`${colors[i]} ${start}% ${end}%`);acc=end});if(acc<100)stops.push(`#ece8e4 ${acc}% 100%`);$('donut').style.background='conic-gradient('+stops.join(',')+')';setText('donutCenter',ratio.toFixed(0)+'%');setText('legCommit',shown(v.commit));setText('legEssential',shown(v.essential));setText('legPersonal',shown(v.personal));setText('legPlan',shown(v.saving+v.investment));setText('legLeft',shown(Math.max(0,v.after)))}
function roundRect(ctx,x,y,w,h,r){if(ctx.roundRect){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}else{ctx.fillRect(x,y,w,h)}}
function prepCanvas(id){const c=$(id),r=c.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,2);c.width=Math.max(300,Math.floor(r.width*dpr));c.height=Math.max(180,Math.floor(r.height*dpr));const ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);return{ctx,w:r.width,h:r.height}}
function drawAnnualChart(v){const {ctx,w,h}=prepCanvas('annualChart'),pad={l:36,r:10,t:12,b:32},cw=w-pad.l-pad.r,ch=h-pad.t-pad.b,vals=[v.income,v.expenses,v.saving,v.investment,Math.max(0,v.after)].map(x=>x*12),labels=['الدخل','المصروف','الادخار','الاستثمار','المتبقي'],cols=['#3b0d1d','#8f7a68','#967128','#245d47','#7a8b91'],max=Math.max(...vals,1);ctx.clearRect(0,0,w,h);ctx.strokeStyle='#e0dad5';for(let i=0;i<4;i++){const y=pad.t+ch*i/3;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke()}const bw=cw/(vals.length*1.7);vals.forEach((val,i)=>{const x=pad.l+(i+.4)*cw/vals.length,y=pad.t+ch-(val/max)*ch;ctx.fillStyle=cols[i];roundRect(ctx,x,y,bw,pad.t+ch-y,5);ctx.fillStyle='#596168';ctx.font='10px Arial';ctx.textAlign='center';ctx.fillText(labels[i],x+bw/2,h-10);ctx.fillStyle='#2a2d31';ctx.font='9px Arial';ctx.fillText(rawMoney(val),x+bw/2,Math.max(11,y-5))})}
function drawTimeline(v){const {ctx,w,h}=prepCanvas('timelineChart'),pad={l:28,r:10,t:16,b:28},cw=w-pad.l-pad.r,ch=h-pad.t-pad.b;ctx.clearRect(0,0,w,h);const max=Math.max((v.saving+v.investment+Math.max(0,v.after))*12,1);ctx.strokeStyle='#e2ddd8';for(let i=0;i<4;i++){let y=pad.t+ch*i/3;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke()}const series=[{v:v.saving,c:'#967128'},{v:v.investment,c:'#245d47'},{v:Math.max(0,v.after),c:'#3b0d1d'}];series.forEach(s=>{ctx.strokeStyle=s.c;ctx.lineWidth=2.5;ctx.beginPath();for(let m=1;m<=12;m++){let x=pad.l+(m-1)*cw/11,y=pad.t+ch-(s.v*m/max)*ch;m===1?ctx.moveTo(x,y):ctx.lineTo(x,y)}ctx.stroke()});ctx.fillStyle='#687078';ctx.font='9px Arial';ctx.textAlign='center';[1,3,6,9,12].forEach(m=>ctx.fillText(String(m),pad.l+(m-1)*cw/11,h-8));ctx.textAlign='right';ctx.fillStyle='#967128';ctx.fillText('ادخار',w-10,12);ctx.fillStyle='#245d47';ctx.fillText('استثمار',w-55,12);ctx.fillStyle='#3b0d1d';ctx.fillText('متبقي',w-112,12)}
function updateSimulation(){const pct=Number($('reductionSlider').value)||0;setText('reductionPct',pct+'%');const cut=current.personal*pct/100,newAfter=current.after+cut;setText('simMonthlySave',money(cut));setText('simAnnualSave',money(cut*12));setText('simAfterPlan',money(newAfter))}
function applyReduction(){const f=1-(Number($('reductionSlider').value)||0)/100;['dining','shopping','subscriptions','travelGifts','otherPersonal'].forEach(id=>{$(id).value=Math.round(n(id)*f)});calc();toast('تم تطبيق التخفيض على الخطة الحالية')}
function saveBaseline(){baseline={...values(),savedAt:Date.now()};safeSet('entwa_budget_baseline_v8',JSON.stringify(baseline));updateComparison();toast('تم حفظ الوضع الحالي كأساس للمقارنة')}
function clearBaseline(){baseline=null;try{localStorage.removeItem('entwa_budget_baseline_v8')}catch(e){}updateComparison();toast('تم مسح المقارنة')}
function updateComparison(){setText('currExpenses',shown(current.expenses));setText('currAfter',shown(current.after));setText('currAnnual',money(current.after*12));if(!baseline){setText('baselineState','لم يتم حفظ خط أساس');setText('baseExpenses','-');setText('baseAfter','-');setText('baseAnnual','-');setText('deltaBox','احفظ خط أساس أولاً ثم عدّل الأرقام لرؤية الفرق.');return}setText('baselineState','خط الأساس محفوظ');setText('baseExpenses',shown(baseline.expenses));setText('baseAfter',shown(baseline.after));setText('baseAnnual',money(baseline.after*12));const d=current.after-baseline.after,spend=baseline.expenses-current.expenses;setText('deltaBox',(d>=0?'تحسن':'انخفاض')+' في المتبقي بعد الخطة بمقدار '+money(Math.abs(d))+' شهرياً ('+money(Math.abs(d)*12)+' سنوياً). '+(spend>0?'انخفضت المصروفات '+money(spend)+' شهرياً.':spend<0?'زادت المصروفات '+money(Math.abs(spend))+' شهرياً.':'المصروفات لم تتغير.'))}
function updateGoal(){const target=n('goalTarget'),cur=n('goalCurrent'),duration=n('goalMonths'),unit=$('goalUnit').value,months=unit==='years'?duration*12:duration;if(!target||!months){setText('goalResult','أدخل هدفك والمدة لرؤية المبلغ المطلوب شهرياً ومقارنته بفائضك الحالي.');return}const gap=Math.max(0,target-cur),need=gap/months,free=Math.max(0,current.after);setText('goalResult','تحتاج تقريباً '+money(need)+' شهرياً للوصول إلى '+money(target)+' خلال '+months+' شهر. '+(free>=need?'فائضك الحالي يغطي هذا المبلغ وفق الأرقام المدخلة.':'ينقصك '+money(need-free)+' شهرياً مقارنة بالفائض الحالي.'))}
function planObject(){const fields={};ids.forEach(i=>fields[i]=$(i).value);return{version:8,app:'ENTWA Budget Workshop',savedAt:new Date().toISOString(),period,fields,baseline,current:values()}}
function persist(){const ok=safeSet('entwa_budget_v8',JSON.stringify(planObject()));setText('saveStatus',ok?'الحفظ التلقائي مفعل على هذا الجهاز.':'تعذر التخزين المحلي؛ استخدم زر «حفظ الخطة» لتنزيل نسخة.')}
async function shareOrDownload(blob,name){const file=new File([blob],name,{type:blob.type||'application/octet-stream'}),isiOS=/iPad|iPhone|iPod/.test(navigator.userAgent);if(isiOS&&navigator.canShare&&navigator.canShare({files:[file]})){try{await navigator.share({files:[file],title:name});return}catch(e){if(e&&e.name==='AbortError')return}}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.target='_blank';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000)}
async function savePlanFile(){persist();const blob=new Blob([JSON.stringify(planObject(),null,2)],{type:'application/json;charset=utf-8'});await shareOrDownload(blob,'ENTWA-ميزانيتي-الخطة.json');toast('تم تجهيز ملف الخطة للحفظ على جهازك')}
function importPlan(ev){const f=ev.target.files&&ev.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result),fields=d.fields||d;ids.forEach(i=>{if(fields[i]!==undefined&&$(i))$(i).value=fields[i]});if(d.baseline){baseline=d.baseline;safeSet('entwa_budget_baseline_v8',JSON.stringify(baseline))}calc();toast('تم استيراد الخطة بنجاح')}catch(e){toast('ملف الخطة غير صالح')}};r.readAsText(f);ev.target.value=''}
function escXml(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;')}
async function exportExcel(){const v=values(),rows=[['المؤشر','شهري','سنوي'],['إجمالي الدخل',v.income,v.income*12],['الالتزامات الأساسية',v.commit,v.commit*12],['المصاريف الأساسية',v.essential,v.essential*12],['المصاريف الشخصية',v.personal,v.personal*12],['إجمالي المصروفات',v.expenses,v.expenses*12],['الادخار المخطط',v.saving,v.saving*12],['الاستثمار المخطط',v.investment,v.investment*12],['المتبقي بعد الخطة',v.after,v.after*12],['هدف صندوق الطوارئ',v.target,v.target],['المتوفر في صندوق الطوارئ',v.emergency,v.emergency]],details=[['البند','القيمة الشهرية'],['الراتب الصافي',n('salary')],['دخل إضافي ثابت',n('extraFixed')],['دخل متغير تقديري',n('extraVariable')],['السكن',n('housing')],['القروض والأقساط',n('loans')],['العمالة المنزلية',n('domestic')],['التأمين والرسوم',n('fixedFees')],['التزام آخر',n('otherCommitment')],['المواد الغذائية',n('groceries')],['الكهرباء والماء والاتصالات',n('utilities')],['المواصلات والوقود',n('transport')],['الصحة والأدوية',n('health')],['التعليم والأبناء',n('education')],['المطاعم والقهوة',n('dining')],['التسوق والعناية',n('shopping')],['الاشتراكات والخدمات',n('subscriptions')],['السفر والهدايا',n('travelGifts')],['مصروف آخر',n('otherPersonal')]];const ws=(name,data)=>`<Worksheet ss:Name="${escXml(name)}"><Table>${data.map(r=>'<Row>'+r.map((c,i)=>`<Cell><Data ss:Type="${i>0&&typeof c==='number'?'Number':'String'}">${escXml(c)}</Data></Cell>`).join('')+'</Row>').join('')}</Table></Worksheet>`;let compare=[['المؤشر','الأساس','الحالي']]; if(baseline)compare.push(['المصروفات',baseline.expenses,v.expenses],['المتبقي بعد الخطة',baseline.after,v.after],['المتبقي السنوي',baseline.after*12,v.after*12]); else compare.push(['الحالة','لم يتم حفظ خط أساس','']);const xml=`<?xml version="1.0" encoding="UTF-8"?><?mso-application progid="Excel.Sheet"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">${ws('الملخص',rows)}${ws('التفاصيل',details)}${ws('المقارنة',compare)}</Workbook>`;const blob=new Blob(['\ufeff'+xml],{type:'application/vnd.ms-excel;charset=utf-8'});await shareOrDownload(blob,'ENTWA-ميزانيتي-الخطة.xls');toast('تم تجهيز ملف Excel')}
function drawPdfReport(v){const c=document.createElement('canvas');c.width=1240;c.height=1754;const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.direction='rtl';ctx.textAlign='right';ctx.fillStyle='#3b0d1d';ctx.fillRect(0,0,c.width,180);ctx.fillStyle='#fff';ctx.font='bold 48px Arial';ctx.fillText('إنتوى | ENTWA',1160,70);ctx.font='bold 42px Arial';ctx.fillText('ميزانيتي قبل الاستثمار — تقرير الخطة',1160,130);ctx.fillStyle='#2a2d31';ctx.font='bold 30px Arial';ctx.fillText('ملخص الوضع المالي',1160,240);const cards=[['إجمالي الدخل',v.income],['إجمالي المصروفات',v.expenses],['الادخار',v.saving],['الاستثمار',v.investment],['المتبقي بعد الخطة',v.after]];cards.forEach((it,i)=>{const col=i%2,row=Math.floor(i/2),cx=1160-col*560,cy=285+row*145;ctx.fillStyle=i===4?'#edf7f1':'#f7f4f1';ctx.fillRect(cx-500,cy,500,110);ctx.fillStyle='#687078';ctx.font='22px Arial';ctx.fillText(it[0],cx-20,cy+38);ctx.fillStyle=i===4?'#245d47':'#3b0d1d';ctx.font='bold 32px Arial';ctx.fillText(money(it[1]),cx-20,cy+82)});let y=745;ctx.fillStyle='#2a2d31';ctx.font='bold 28px Arial';ctx.fillText('الخطة السنوية',1160,y);const annual=[['الدخل',v.income*12,'#3b0d1d'],['المصروف',v.expenses*12,'#8f7a68'],['الادخار',v.saving*12,'#967128'],['الاستثمار',v.investment*12,'#245d47'],['المتبقي',Math.max(0,v.after*12),'#7a8b91']],max=Math.max(...annual.map(a=>a[1]),1);annual.forEach((a,i)=>{const yy=y+65+i*95;ctx.fillStyle='#ece8e4';ctx.fillRect(200,yy,850,34);ctx.fillStyle=a[2];ctx.fillRect(200,yy,850*(a[1]/max),34);ctx.fillStyle='#2a2d31';ctx.font='22px Arial';ctx.fillText(a[0]+'  '+money(a[1]),1160,yy+28)});y=1310;ctx.fillStyle='#2a2d31';ctx.font='bold 28px Arial';ctx.fillText('صندوق الطوارئ والهدف المالي',1160,y);const gap=Math.max(0,v.target-v.emergency),eta=gap===0?'مكتمل':v.emergencyContribution?Math.ceil(gap/v.emergencyContribution)+' شهر':'لم يتم تحديد مساهمة شهرية';ctx.font='22px Arial';ctx.fillStyle='#4f565c';ctx.fillText('هدف صندوق الطوارئ: '+money(v.target),1160,y+55);ctx.fillText('المتوفر حالياً: '+money(v.emergency)+' — المتبقي: '+money(gap),1160,y+95);ctx.fillText('المدة التقديرية للوصول: '+eta,1160,y+135);const gt=n('goalTarget'),gc=n('goalCurrent'),gd=n('goalMonths'),gu=$('goalUnit').value,gmonths=gu==='years'?gd*12:gd;if(gt&&gmonths){const need=Math.max(0,gt-gc)/gmonths;ctx.fillText('الهدف المالي: '+money(gt)+' — المطلوب تقريباً '+money(need)+' شهرياً',1160,y+185)}ctx.fillStyle='#8a8f94';ctx.font='18px Arial';ctx.fillText('هذه الأداة تعليمية ولا تفترض أي عوائد استثمارية.',1160,1680);return c}
function jpegToPdf(jpegBytes,wpx,hpx){const enc=s=>new TextEncoder().encode(s),parts=[],offsets=[0];let len=0;const add=b=>{parts.push(b);len+=b.length},addObj=(num,body)=>{offsets[num]=len;add(enc(`${num} 0 obj\n${body}\nendobj\n`))};add(enc('%PDF-1.4\n'));addObj(1,'<< /Type /Catalog /Pages 2 0 R >>');addObj(2,'<< /Type /Pages /Kids [3 0 R] /Count 1 >>');addObj(3,'<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /XObject << /Im0 4 0 R >> >> /Contents 5 0 R >>');offsets[4]=len;add(enc(`4 0 obj\n<< /Type /XObject /Subtype /Image /Width ${wpx} /Height ${hpx} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpegBytes.length} >>\nstream\n`));add(jpegBytes);add(enc('\nendstream\nendobj\n'));const content=enc('q 595 0 0 842 0 0 cm /Im0 Do Q');offsets[5]=len;add(enc(`5 0 obj\n<< /Length ${content.length} >>\nstream\n`));add(content);add(enc('\nendstream\nendobj\n'));const xref=len;add(enc('xref\n0 6\n0000000000 65535 f \n'));for(let i=1;i<=5;i++)add(enc(String(offsets[i]).padStart(10,'0')+' 00000 n \n'));add(enc(`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`));const out=new Uint8Array(len);let p=0;parts.forEach(b=>{out.set(b,p);p+=b.length});return out}
async function exportPDF(){const btn=$('pdfBtn'),old=btn.textContent;btn.textContent='جاري تجهيز PDF...';btn.disabled=true;try{const c=drawPdfReport(values()),data=c.toDataURL('image/jpeg',0.9).split(',')[1],bin=atob(data),jpg=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)jpg[i]=bin.charCodeAt(i);const pdf=jpegToPdf(jpg,c.width,c.height),blob=new Blob([pdf],{type:'application/pdf'});await shareOrDownload(blob,'ENTWA-ميزانيتي-التقرير.pdf');toast('تم تجهيز ملف PDF')}catch(e){console.error(e);toast('تعذر إنشاء PDF. جرّب فتح الرابط في Safari ثم أعد المحاولة.')}finally{btn.textContent=old;btn.disabled=false}}
function resetData(){if(confirm('هل تريد مسح جميع البيانات؟')){try{localStorage.removeItem('entwa_budget_v8');localStorage.removeItem('entwa_budget_baseline_v8')}catch(e){}baseline=null;ids.forEach(i=>{$(i).value=i==='emergencyMonths'?'6':i==='goalUnit'?'months':''});$('reductionSlider').value=10;calc();toast('تمت إعادة التعيين')}}
function load(){let d={};try{const saved=JSON.parse(safeGet('entwa_budget_v8','{}'));d=saved.fields||saved;baseline=JSON.parse(safeGet('entwa_budget_baseline_v8','null'))}catch(e){}ids.forEach(i=>{if(d[i]!==undefined&&$(i))$(i).value=d[i]});calc()}
ids.forEach(i=>{const el=$(i);if(el){el.addEventListener('input',calc);el.addEventListener('change',calc)}});$('reductionSlider').addEventListener('input',updateSimulation);window.addEventListener('resize',()=>{drawAnnualChart(current);drawTimeline(current)});load();